variables:
  MAVEN_CLI_OPTS: "-B --no-transfer-progress -e -DexecutionEnvironment=CICD $MAVEN_CLI_JOB_OPTS"
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository -Djdk.net.URLClassPath.disableClassPathURLCheck=true -Dhttps.protocols=TLSv1.2 -Djava.awt.headless=true"
  CICD_REPO_GIT_REF: master

stages:
  - .pre
  - build
  - deploy_panda
  - deploy

.base_tags:
  tags: [ atmosphere ]


################################################################################
# Version
################################################################################
.create_release_version_base:
  extends: .base_tags
  image: hub.docker.nexus.ocado.tech/maven:3.8.7-eclipse-temurin-17-alpine
  stage: .pre
  before_script:
    - export NEXUS_PASSWORD=$OSP_FLUX_RW_NEXUS_PASSWORD
    - export NEXUS_USERNAME=$OSP_FLUX_RW_NEXUS_USER
    - apk add -Uq --no-progress curl
    - mkdir -p ~/.m2 && curl -sSL https://gitlab-ci-token:$CI_BUILD_TOKEN@$CI_SERVER_HOST/flux/cicd/raw/${CICD_REPO_GIT_REF}/infra/settings.xml -o ~/.m2/settings.xml
    - mvn -q $MAVEN_CLI_OPTS help:evaluate -Dexpression=base.version -DforceStdout | tee .base-version
    - BASE_VERSION=$(cat .base-version)
    # Replaces all non-alphanumeric characters by underscored and takes the first 10 chars of the branch name
    - BRANCH_SHORT_NAME=$(echo $CI_COMMIT_REF_NAME | sed -r "s/[^A-Za-z0-9]+/_/g" | cut -c -10)
    - '[ "$CI_COMMIT_REF_NAME" != "$CI_DEFAULT_BRANCH" ] && RELEASE_VERSION_BRANCH_SUFFIX="-$BRANCH_SHORT_NAME-$CI_PIPELINE_ID-SNAPSHOT"'
    - RELEASE_VERSION=$BASE_VERSION-$(date +%Y.%m.%d)-$CI_COMMIT_SHORT_SHA$RELEASE_VERSION_BRANCH_SUFFIX
    - echo $RELEASE_VERSION > .release-version
    - 'echo Release: $RELEASE_VERSION'
  artifacts:
    name: version
    paths: [.release-version]
    expire_in: 12 months
  cache: {}

create_release_version:
  extends: .create_release_version_base
  script:
    - echo default create_release_version complete

.build_jar_base:
  extends: .base_tags
  image: hub.docker.nexus.ocado.tech/maven:3.8.7-eclipse-temurin-17-alpine
  stage: build
  before_script:
    - export NEXUS_PASSWORD=$OSP_FLUX_RW_NEXUS_PASSWORD
    - export NEXUS_USERNAME=$OSP_FLUX_RW_NEXUS_USER
    - mkdir -p ~/.m2 && curl -sSL https://gitlab-ci-token:$CI_BUILD_TOKEN@$CI_SERVER_HOST/flux/cicd/raw/${CICD_REPO_GIT_REF}/infra/settings.xml -o ~/.m2/settings.xml
  script:
    - echo release-version $(cat .release-version)
    - export RELEASE_VERSION=$(cat .release-version)
    - mvn $MAVEN_CLI_OPTS install -pl ${MODULE} -am -Drevision=$RELEASE_VERSION
  artifacts:
    name: application-jar
    paths: [./*/target/spring-petclinic-*.jar]
    expire_in: 12 months
  needs: [create_release_version]

.deploy_chancellor_base:
  image: registry.gitlab.ocado.tech/chancellor-cli/chancellor-cli:3.10.2-alpine
  stage: deploy
  script:
    - echo release-version $(cat .release-version)
    - export RELEASE_VERSION=$(cat .release-version)
    - chancellor image build -m infra/chancellor-cli-templates/image-builder-metadata.json -a ./${MODULE}/target/${MODULE}-${RELEASE_VERSION}.jar
    - chancellor service deploy --descriptor=./infra/chancellor-cli-templates/image-builder-deployment.json -d ${DTAP} -b ${BUSINESS_ID} -a $APP_ID -A ${ALIAS}
  variables:
    DTAP: dev
    BUSINESS_ID: atm
    ALIAS: use1
  when: manual

.deploy_panda_base:
  image: registry.gitlab.ocado.tech/chancellor-cli/chancellor-cli:3.10.2-alpine
  stage: deploy_panda
  script:
    - export PANDA_PROPERTIES_FILE="./infra/${APP_ID}_panda.json"
    - chancellor configuration panda deploy -d "$DTAP" -b "$BUSINESS_ID" -a "$APP_ID" -A "$ALIAS" -c "$PANDA_PROPERTIES_FILE"
  variables:
    DTAP: dev
    BUSINESS_ID: atm
    ALIAS: use1
  when: manual

build_frontend:
  extends: .build_jar_base
  variables:
    MODULE: spring-petclinic-api-gateway

deploy_frontend:
  extends: .deploy_chancellor_base
  variables:
    MODULE: spring-petclinic-api-gateway
    APP_ID: petclinic
  needs:
    - build_frontend
    - create_release_version

deploy_panda_frontend:
  extends: .deploy_panda_base
  variables:
    MODULE: spring-petclinic-api-gateway
    APP_ID: petclinic
  needs:
    - build_frontend
    - create_release_version

build_customers_service:
  extends: .build_jar_base
  variables:
    MODULE: spring-petclinic-customers-service

deploy_customers_service:
  extends: .deploy_chancellor_base
  variables:
    MODULE: spring-petclinic-customers-service
    APP_ID: petcliniccustomersservice
  needs:
    - build_customers_service
    - create_release_version

deploy_panda_customers_service:
  extends: .deploy_panda_base
  variables:
    MODULE: spring-petclinic-customers-service
    APP_ID: petcliniccustomersservice
  needs:
    - build_customers_service
    - create_release_version

build_vets_service:
  extends: .build_jar_base
  variables:
    MODULE: spring-petclinic-vets-service

deploy_vets_service:
  extends: .deploy_chancellor_base
  variables:
    MODULE: spring-petclinic-vets-service
    APP_ID: petclinicvetsservice
  needs:
    - build_vets_service
    - create_release_version

deploy_panda_vets_service:
  extends: .deploy_panda_base
  variables:
    MODULE: spring-petclinic-vets-service
    APP_ID: petclinicvetsservice
  needs:
    - build_vets_service
    - create_release_version

build_visits_service:
  extends: .build_jar_base
  variables:
    MODULE: spring-petclinic-visits-service

deploy_visits_service:
  extends: .deploy_chancellor_base
  variables:
    MODULE: spring-petclinic-visits-service
    APP_ID: petclinicvisitsservice
  needs:
    - build_visits_service
    - create_release_version

deploy_panda_visits_service:
  extends: .deploy_panda_base
  variables:
    MODULE: spring-petclinic-visits-service
    APP_ID: petclinicvisitsservice
  needs:
    - build_visits_service
    - create_release_version
