server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: app-logs
  static_configs:
    - targets:
        - localhost
      labels:
        job: api-gateway
        __path__: /var/log/app-logs/api-gateway.log.json
    - targets:
        - localhost
      labels:
        job: customer-service
        __path__: /var/log/app-logs/customer-service.log.json
    - targets:
        - localhost
      labels:
        job: vets-service
        __path__: /var/log/app-logs/vets-service.log.json
    - targets:
        - localhost
      labels:
        job: visits-service
        __path__: /var/log/app-logs/visits-service.log.json
  pipeline_stages:
    - match:
        selector: '{job=~".+"}'
        stages:
          - json:
              expressions:
                timestamp: timestamp
                level: level
                thread: thread
                logger: logger
                message: message
                exception: exception
                mdc: mdc
          - json:
              expressions:
                traceId:
                spanId:
              source: mdc
          - labels:
              level:
              logger:
              traceId:
              spanId:
#          - timestamp:
#              format: RFC3339Nano
#              source: timestamp
          - output:
              source: output
