# config file version
apiVersion: 1

# list of datasources to insert/update depending what's available in the database
datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
  jsonData:
    httpMethod: GET
    exemplarTraceIdDestinations:
    - datasourceUid: tempo
      name: trace_id
- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  jsonData:
    httpMethod: GET
    datasourceUid: loki
    serviceMap:
      datasourceUid: prometheus
    "lokiSearch":
      "datasourceUid": "loki"
    "nodeGraph":
      "enabled": true
    tracesToLogs:
      "datasourceUid": "loki"
      "mapTagNamesEnabled": false,
      "tags":
         - "net.host.ip"
    tracesToMetrics:
      "datasourceUid": "prometheus"

- name: Loki
  type: loki
  uid: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: '"traceId":"(\w+)"'
        name: TraceID
        url: $${__value.raw}
- name: Elasticsearch
  type: elasticsearch
  orgId: 1
  uid: elasticsearch
  typeLogoUrl: ''
  access: proxy
  url: http://elasticsearch:9200
  user: ''
  database: ''
  basicAuth: true
  basicAuthUser: elastic
  withCredentials: false
  isDefault: false
  jsonData:
    esVersion: 8.0.0
    includeFrozen: false
    logLevelField: ''
    logMessageField: ''
    maxConcurrentShardRequests: 5
    timeField: "@timestamp"
    tlsAuthWithCACert: false
    basicAuthPassword: +kKvULi=4qpvFtIOj9Nh
    dataLinks:
      - datasourceUid: tempo
        field: traceId
        url: "${__value.raw}"
#  secureJsonFields:
#    basicAuthPassword: true
#    tlsCACert: false
  version: 5
  readOnly: false
  editable: true
  accessControl:
    alert.instances.external:read: true
    alert.instances.external:write: true
    alert.notifications.external:read: true
    alert.notifications.external:write: true
    alert.rules.external:read: true
    alert.rules.external:write: true
    datasources.id:read: true
    datasources:delete: true
    datasources:query: true
    datasources:read: true
    datasources:write: true


# elastic u:elastic p:FBYS7eMEhVmGn3coVE88
# elastic u:elastic p:+kKvULi=4qpvFtIOj9Nh
