# config file version
apiVersion: 1

# list of datasources to insert/update depending what's available in the database
datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
  jsonData:
    httpMethod: GET
    exemplarTraceIdDestinations:
    - datasourceUid: tempo
      name: trace_id
- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  jsonData:
    httpMethod: GET
    datasourceUid: loki
    serviceMap:
      datasourceUid: prometheus
    "lokiSearch":
      "datasourceUid": "loki"
    "nodeGraph":
      "enabled": true
    tracesToLogs:
      "datasourceUid": "loki"
      "mapTagNamesEnabled": false,
      "tags":
         - "net.host.ip"
    tracesToMetrics:
      "datasourceUid": "prometheus"

- name: Loki
  type: loki
  uid: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: '"traceId":"(\w+)"'
        name: TraceID
        url: $${__value.raw}

